[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11.0"
regex = "1.12.2"
rustc-hash = "2.1.1"
smallvec = { version = "1.15.1", features = ["const_generics"] }
z3 = { version = "0.19.5", features = ["static-link-z3"] }
